name: Deploy YoYakZom API

on:
  push:
  pull_request:
    branches: [ main ]# main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v4.2.2

      # - name: Node.js 설정
      #   uses: actions/setup-node@v4.1.0
      #   with:
      #     node-version: 'v17.9.1'  # 프로젝트에 맞는 Node.js 버전 지정

      # - name: dependency install
      #   run: npm install

      # - name: application build
      #   run: npm run build

      # - name: sshpass install
      #   run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH connection with password
        uses: appleboy/ssh-action@v1.1.0
        env:
          db_host: ${{ secrets.DB_HOST }}
          db_port: ${{ secrets.DB_PORT }}
          db_username: ${{ secrets.DB_USERNAME }}
          db_password: ${{ secrets.DB_PASSWORD }}
          db_schema: ${{ secrets.DB_SCHEMA }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: whoami
